kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: console-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-console-db-data
  namespace: console
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: console-local-storage
  local:
    path: "/home/jar/pv/db-data"
  claimRef:
    namespace: console
    name: db-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubtest3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-console-restapi-domains
  namespace: console
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: console-local-storage
  local:
    path: "/home/jar/pv/restapi-domains"
  claimRef:
    namespace: console
    name: restapi-domains
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubtest3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-console-aip-node-cast
  namespace: console
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: console-local-storage
  local:
    path: "/home/jar/pv/CAST"
  claimRef:
    namespace: console
    name: aip-node-cast
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubtest2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-console-aip-node-data
  namespace: console
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: console-local-storage
  local:
    path: "/home/jar/pv/aip-node-data"
  claimRef:
    namespace: console
    name: aip-node-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kubtest2
