apiVersion: v1
kind: Service
metadata:
  labels:
    console.service: aip-gateway
  name: aip-gateway
  namespace: {{ .Release.Namespace }}   
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    console.service: aip-gateway  
  type: NodePort 