apiVersion: v1
kind: Service
metadata:
  labels:
    console.service: aip-node
  name: aip-node
  namespace: {{ .Release.Namespace }}  
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    console.service: aip-node  
  type: NodePort  