apiVersion: v1
kind: Service
metadata:
  labels:
    console.service: aip-service-registry
  name: aip-service-registry
  namespace: {{ .Release.Namespace }}  
spec:
  ports:
    - name: "2281"
      port: 2281
      targetPort: 2281
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    console.service: aip-service-registry
  type: NodePort    