apiVersion: v1
kind: Service
metadata:
  labels:
    console.service: postgres
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: "2285"
      port: 2285
      targetPort: 5432
  selector:
    console.service: postgres
  type: NodePort