apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    console.service: postgres
    # version: {{.Values.PostgresImage.tag| default .Values.version}}
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.PostgresReplicaCount }}
  selector:
    matchLabels:
      console.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        console.network/aip-network: "true"
        console.service: postgres
    spec:   
      containers:
        - env:
            - name: POSTGRES_INITDB_ARGS
              value: -E 'UTF-8' --lc-collate=C --lc-ctype=C
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: "{{ .Values.PostgresImage.name }}:{{ .Values.PostgresImage.tag}}"
          imagePullPolicy: "{{ .Values.PostgresImage.pullPolicy }}"
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: postgres
          ports:
            - containerPort: 5432
              hostPort: 2285
              protocol: TCP
          resources:
            {{- toYaml .Values.PostgresResources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
            - name: pgconf
              mountPath: "/usr/pgsql-13/share/postgresql.conf.sample"              
              subPath: postgresql.conf.sample
            - name: pginit
              mountPath: "/docker-entrypoint-initdb.d/init-db.sh"               
              subPath: init-db.sh
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data           
        - name: pgconf
          configMap:
            name: postgresqlconf
            defaultMode: 0777     
        - name: pginit
          configMap:
            name: init-db
            defaultMode: 0777   